### ISSUE TITLE
graphcast_operational_for_copy的download_ncep.py是不是需要更新一下

### ISSUE THREAD

**Issue by JeffDing** [yungyun0721/AI_global_forecast_model_for_education#2]
graphcast_operational_for_copy的download_ncep.py运行会有以下报错：
```text
 datetime_test =  pd.array([f'{timestr_front[:4]}-{timestr_front[4:6]}-{timestr_front[6:8]}T{timestr_front[8:]}:00:00.000000000', f'{timestr[:4]}-{timestr[4:6]}-{timestr[6:8]}T{timestr[8:]}:00:00.000000000'], dtype='datetime64').reshape([1,-1])
Traceback (most recent call last):
  File "/tmp/code/ai_global_forecast_model_for_education/graphcast_operational_for_copy/download_ncep.py", line 97, in <module>
    main(args.scheduled_time)    
  File "/tmp/code/ai_global_forecast_model_for_education/graphcast_operational_for_copy/download_ncep.py", line 89, in main
    inputs_ds.to_netcdf(save_path)
  File "/opt/conda/lib/python3.10/site-packages/xarray/core/dataset.py", line 2338, in to_netcdf
    return to_netcdf(  # type: ignore[return-value]  # mypy cannot resolve the overloads:(
  File "/opt/conda/lib/python3.10/site-packages/xarray/backends/api.py", line 1420, in to_netcdf
    dump_to_store(
  File "/opt/conda/lib/python3.10/site-packages/xarray/backends/api.py", line 1467, in dump_to_store
    store.store(variables, attrs, check_encoding, writer, unlimited_dims=unlimited_dims)
  File "/opt/conda/lib/python3.10/site-packages/xarray/backends/common.py", line 364, in store
    variables, attributes = self.encode(variables, attributes)
  File "/opt/conda/lib/python3.10/site-packages/xarray/backends/common.py", line 453, in encode
    variables, attributes = cf_encoder(variables, attributes)
  File "/opt/conda/lib/python3.10/site-packages/xarray/conventions.py", line 801, in cf_encoder
    _update_bounds_encoding(variables)
  File "/opt/conda/lib/python3.10/site-packages/xarray/conventions.py", line 357, in _update_bounds_encoding
    is_datetime_type = np.issubdtype(
  File "/opt/conda/lib/python3.10/site-packages/numpy/core/numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
TypeError: Cannot interpret 'NumpyEADtype('datetime64[ns]')' as a data type
```

感觉是不是代码需要更新一下？还是库版本问题？

**Comment by yungyun0721** [comment]
我改一下寫法(已update)
你可以再試試看~
